$('.owl-carousel').owlCarousel({
    loop:true,
    margin:15,
    nav:true,
    responsive:{
        0:{
            items:1
        },
        350:{
            items:3
        },
        600:{
            items:5
        },
        1000:{
            items:9
        }
    }
})